server:
  port: 9000

messages:
  batchSize: 3
  maxWaitTimeout: 30
  maxWaitTimeUnit: SECONDS
  poolSize: 2

app:
  enrichedMessagesTopic: enriched-messages
  payloadMessagesTopic: payload-messages

spring:
  jooq:
    sql-dialect: POSTGRES

  datasource:
    url: jdbc:postgresql://localhost:5432/app
    username: app
    password: app
    driverClassName: org.postgresql.Driver
  kafka:
    consumer:
      bootstrap-servers: localhost:9092

    producer:
      bootstrap-servers: localhost:9092