server:
  port: 9000

messages:
  batchSize: 100
  maxWaitTimeout: 30
  maxWaitTimeUnit: SECONDS
  poolSize: 2

app:
  enrichedMessagesTopic: enriched-messages
  enrichedMessagesPartitions: 3
  payloadMessagesTopic: payload-messages
  concurrentListeners: 3

spring:
  jooq:
    sql-dialect: POSTGRES

  datasource:
    url: jdbc:postgresql://localhost:5432/app
    username: app
    password: app
    driverClassName: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9092